#! /bin/bash

if [[ $# -ne 1 || $1 == "-h" || $1 == "--help" ]]; then
    echo "Usage: set_lesson.sh <lesson number>"
    exit 1
fi

if [[ ! -d "./lesson_archive/$1" ]]; then
    mkdir -p "./lesson_archive/$1/templates"
    touch ./lesson_archive/$1/app.py
    chmod +x ./lesson_archive/$1/app.py
fi

ln -sf ./lesson_archive/$1/app.py .
ln -sf ./lesson_archive/$1/templates .
